### ISSUE TITLE
Investigate adding implementation for imposters

### ISSUE THREAD

**Issue by hogsy** [TalonBraveInfo/platform#12]
https://www.gamasutra.com/view/feature/130911/dynamic_2d_imposters_a_simple_.php

**Comment by DummkopfOfHachtenduden** [comment]
http://www.shaderbits.com/blog/octahedral-impostors

**Comment by hogsy** [comment]
Should be moved across to OpenHoW project, but I'll close this for now as it's just something to consider in the future.
